# Configuration for Release Drafter
# https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🎨 Style'
    labels:
      - 'style'
  - title: '♻️ Refactor'
    labels:
      - 'refactor'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '✅ Tests'
    labels:
      - 'test'
  - title: '🔧 Build'
    labels:
      - 'build'
      - 'ci'
      - 'cd'

template: |
  ## 🎉 What's Changed

  $CHANGES

  ## 📋 Full Changelog

  $CHANGES

  ## 🚀 Installation

  ```bash
  npm install
  npm run dev
  ```

  ## 📚 Documentation

  See the [README](https://github.com/your-username/djs-frontend-development#readme) for full documentation.

  ## 🤝 Contributing

  Contributions are welcome! Please see our [Contributing Guide](CONTRIBUTING.md).

  ---

  **Note**: This is an educational project for learning frontend development with JavaScript and TypeScript.
