# Configuration for Stale Bot
# https://github.com/actions/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - education
  - learning
  - example

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: false

# Set to true to ignore issues with a specific label (defaults to false)
exemptAllLabels: false

# Labels to take away when a stale issue is closed
closedIssueLabels:
  - stale

# Limit to n issues per run, use 0 for no limit
limitPerRun: 0

# Optionally, specify configuration for pull requests
pullRequests:
  # Number of days of inactivity before a PR becomes stale
  daysUntilStale: 60

  # Number of days of inactivity before a stale PR is closed
  daysUntilClose: 7

  # PRs with these labels will never be considered stale
  exemptLabels:
    - pinned
    - security
    - work-in-progress
    - education
    - learning

  # Set to true to ignore PRs in a milestone (defaults to false)
  exemptMilestones: false

  # Set to true to ignore PRs with an assignee (defaults to false)
  exemptAssignees: false

  # Set to true to ignore PRs with a specific label (defaults to false)
  exemptAllLabels: false

  # Labels to take away when a stale PR is closed
  closedPrLabels:
    - stale

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to inactivity. If you believe
  this issue should remain open, please comment with a reason why. Thank you
  for your contributions.

# Limit to n issues per run, use 0 for no limit
limitPerRun: 0
