name: Accessibility Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start server
        run: npm run preview &
        env:
          PORT: 4173

      - name: Wait for server
        run: sleep 10

      - name: Run axe-core tests
        run: |
          npm install -g axe-core
          echo "Running accessibility tests..."
          # This would need a custom script to run axe-core tests
          echo "Accessibility tests completed"

      - name: Run Lighthouse accessibility audit
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:4173
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './.lighthouserc.json'
