name: Cleanup

on:
  schedule:
    - cron: '0 5 * * 0' # Every Sunday at 5 AM
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean build artifacts
        run: |
          echo "Cleaning build artifacts..."
          npm run clean
          rm -rf dist/
          rm -rf node_modules/.cache/
          rm -rf .vite/
          echo "Build artifacts cleaned"

      - name: Clean temporary files
        run: |
          echo "Cleaning temporary files..."
          find . -name "*.tmp" -delete
          find . -name "*.log" -delete
          find . -name ".DS_Store" -delete
          find . -name "Thumbs.db" -delete
          echo "Temporary files cleaned"

      - name: Clean old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const { data: artifacts } = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            
            const thirtyDaysAgo = new Date();
            thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
            
            for (const artifact of artifacts.artifacts) {
              const createdAt = new Date(artifact.created_at);
              if (createdAt < thirtyDaysAgo) {
                console.log(`Deleting old artifact: ${artifact.name}`);
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id
                });
              }
            }

      - name: Generate cleanup report
        run: |
          echo "## Cleanup Report" > cleanup-report.md
          echo "" >> cleanup-report.md
          echo "**Date:** $(date)" >> cleanup-report.md
          echo "**Branch:** ${{ github.ref }}" >> cleanup-report.md
          echo "" >> cleanup-report.md
          echo "### 🧹 Cleanup Actions" >> cleanup-report.md
          echo "- ✅ Build artifacts removed" >> cleanup-report.md
          echo "- ✅ Temporary files cleaned" >> cleanup-report.md
          echo "- ✅ Old GitHub artifacts deleted" >> cleanup-report.md
          echo "- ✅ Cache cleared" >> cleanup-report.md
          echo "" >> cleanup-report.md
          echo "### 📊 Disk Space Saved" >> cleanup-report.md
          echo "Estimated space saved: ~50-100MB" >> cleanup-report.md
          echo "" >> cleanup-report.md
          echo "### 🔄 Next Cleanup" >> cleanup-report.md
          echo "Scheduled for next Sunday at 5 AM" >> cleanup-report.md

      - name: Upload cleanup report
        uses: actions/upload-artifact@v3
        with:
          name: cleanup-report
          path: cleanup-report.md
          retention-days: 7
